#FSR Autogenerated Content. DO NOT DELETE
from .get_feed import get_feed
from .get_sample_feed import get_sample_feed
 
supported_operations = {'get_feed': get_feed, 'get_sample_feed': get_sample_feed, }